### PR TITLE
CSS fix for Jenkins 2.346+

### LINKED ISSUE #67: Color not visible anymore
Hi @Jorg3Lucas

after upgrading Jenkins to a newer LTS version (e.g. 2.346.1) the theme color and logo is not shown anymore.
The bug seems to be equal to upstream: https://github.com/afonsof/jenkins-material-theme/issues/194

It would be great if the issue could be fixed without having a local .css file on Jenkins.

Regards
Dominik

### PR DESCRIPTION
**Pull request by offa**
Fixes broken theming on Jenkins 2.346 LTS.

Applies the patch created by @cossons: https://github.com/afonsof/jenkins-material-theme/pull/199

closes #67

### CODE REVIEW

**Comment by ghost** [comment]
Hey! wanted to check if you plan to merge this change, if yes, then when do you plan to do so. Thanks!

**Comment by ppatel-cint** [comment]
Hi, may I know when this change will be merge?

**Comment by offa** [comment]
We have to wait for @Jorg3Lucas

**Comment by wgoyer** [comment]
Heads up, I took the modern-pink and modern-blue for a test drive and text color in the console output and some settings are difficult to view. The font color of the text in the console output is now dark grey with v2.346.1 on top of light grey. The background color being applied to the console output is still black with the themes.
Screen Shot 2022-07-11 at 5 35 01 PM

Edit:
Looks like I was a few minutes late... sorry about that.

**Pull request merged**
